DROP DATABASE IF EXISTS cars_db;
CREATE DATABASE cars_db;


CREATE TABLE make(
id INT(100) AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100)
);

CREATE TABLE Acura(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Alfa Romeo(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Aston Martin(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Audi(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Bentley(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE BMW(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Bugatti(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Buick(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Cadillac(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Chevrolet(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Chrysler(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Dodge(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Ferrari(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Fiat(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Ford(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE GMC(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Honda(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Hyundai(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Infiniti(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Jaguar(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Jeep(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Kia(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Lamborghini(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Land Rover(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Lexus(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Maserati(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Mazda(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE McLaren(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Mercedes-Benz(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Mini(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Mitsubishi(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Porsche(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Nissan(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE RAM(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Rolls Royce(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE SAAB(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Subaru(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Suzuki(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Tesla(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Toyota(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Volkswagen(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);
CREATE TABLE Volvo(
    id INT(100) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);